### ISSUE TITLE
Only one scaffold generated using the included example?

### ISSUE THREAD

**Issue by charlesklee** [rvicedomini/strainberry#4]
Using the latest version of 2021-03-25 (v1.0?) and *assembly.fasta* and *alignmen.sorted.bam* in the *example* folder, I only get one scaffold in the resulting assembly.scaffolds.fa. I received no obvious error messages.

**Comment by rvicedomini** [comment]
Thank you for reporting the issue.
A major update of Strainberry will be released soon. It is possible that this update will either solve the issue or better produce error messages in case something goes wrong. Hopefully, I will release it within a week.

**Comment by rvicedomini** [comment]
It took me a bit longer than expected, but a major update of Strainberry has been released.
I also added a github action that tests the tool on the example data and it does not show any issue.

Therefore, I'm closing this issue as the reported problem might have been fixed.
